name: Build and Test

on:
  push:
    branches: [ main, breakout]
  pull_request:
    branches: [ main, breakout]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: building and testing
      run: |
        ./cmakew -t .